CREATE TABLE IF NOT EXISTS document_types (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (char_length(name) > 3)
);

ALTER TABLE document_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Individuals can create new Document Types." ON document_types FOR
INSERT
    TO authenticated
WITH
    CHECK (TRUE);

CREATE POLICY "Individuals can read all Document Types." ON document_types FOR
SELECT TO authenticated USING (TRUE);