CREATE TABLE IF NOT EXISTS work_types (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (char_length(name) > 3)
);

ALTER TABLE work_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Individuals can create new Work Types." ON work_types FOR
INSERT
    TO authenticated
WITH
    CHECK (TRUE);

CREATE POLICY "Individuals can read all Work Types." ON work_types FOR
SELECT TO authenticated USING (TRUE);