CREATE TABLE IF NOT EXISTS cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (char_length(name) > 3),
    country_id SMALLINT REFERENCES countries NOT NULL
);

ALTER TABLE cities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Individuals can create new Cities." ON cities FOR
INSERT
    TO authenticated
WITH
    CHECK (TRUE);

CREATE POLICY "Individuals can read all Cities." ON cities FOR
SELECT TO authenticated USING (TRUE);