CREATE TABLE IF NOT EXISTS todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT REFERENCES applications ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    due_date DATE,
    status BOOLEAN DEFAULT FALSE
);

ALTER TABLE todos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Individuals can create new Todos." ON todos FOR
INSERT
    TO authenticated
WITH
    CHECK (
        (
            SELECT auth.uid ()
        ) = (
            SELECT user_id
            FROM applications
            WHERE
                id = application_id
        )
    );

CREATE POLICY "Individuals can read their Todos." ON todos FOR
SELECT TO authenticated USING (
        (
            SELECT auth.uid ()
        ) = (
            SELECT user_id
            FROM applications
            WHERE
                id = application_id
        )
    );

CREATE POLICY "Individuals can update their Todos." ON todos FOR
UPDATE TO authenticated USING (
    (
        SELECT auth.uid ()
    ) = (
        SELECT user_id
        FROM applications
        WHERE
            id = application_id
    )
)
WITH
    CHECK (
        (
            SELECT auth.uid ()
        ) = (
            SELECT user_id
            FROM applications
            WHERE
                id = application_id
        )
    );

CREATE POLICY "Individuals can delete their Todos." ON todos FOR DELETE TO authenticated USING (
    (
        SELECT auth.uid ()
    ) = (
        SELECT user_id
        FROM applications
        WHERE
            id = application_id
    )
);