CREATE TABLE IF NOT EXISTS company_types (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (char_length(name) > 3)
);

ALTER TABLE company_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Individuals can create new Company Types." ON company_types FOR
INSERT
    TO authenticated
WITH
    CHECK (TRUE);

CREATE POLICY "Individuals can read all Company Types." ON company_types FOR
SELECT TO authenticated USING (TRUE);