CREATE TABLE IF NOT EXISTS countries (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (char_length(name) > 3)
);

ALTER TABLE countries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Individuals can create new Countries." ON countries FOR
INSERT
    TO authenticated
WITH
    CHECK (TRUE);

CREATE POLICY "Individuals can read all Countries." ON countries FOR
SELECT TO authenticated USING (TRUE);