CREATE TABLE IF NOT EXISTS status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (char_length(name) > 3)
);

ALTER TABLE status ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Individuals can create new Status." ON status FOR
INSERT
    TO authenticated
WITH
    CHECK (TRUE);

CREATE POLICY "Individuals can read all Status." ON status FOR
SELECT TO authenticated USING (TRUE);